name: run-tests

on:
  push:
    branches: [main, 2.x]
  pull_request:
    branches: [main, 2.x]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - php: 8.4
            symfony: '7.1'
          - php: 8.4
            symfony: '7.0'
          - php: 8.4
            symfony: '6.4'
          - php: 8.3
            symfony: '7.1'
          - php: 8.3
            symfony: '7.0'
          - php: 8.3
            symfony: '6.4'
          - php: 8.2
            symfony: '7.1'
          - php: 8.2
            symfony: '7.0'
          - php: 8.2
            symfony: '6.4'
          - php: 8.1
            symfony: '6.4'

    name: PHP ${{ matrix.php }} - Symfony ${{ matrix.symfony }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Require Symfony version
        run: |
          composer require "symfony/framework-bundle:^${{ matrix.symfony }}" "symfony/http-kernel:^${{ matrix.symfony }}" "symfony/console:^${{ matrix.symfony }}" "symfony/config:^${{ matrix.symfony }}" "symfony/dependency-injection:^${{ matrix.symfony }}" "symfony/event-dispatcher:^${{ matrix.symfony }}" --no-interaction --no-update

      - name: Install dependencies
        run: composer update --prefer-stable --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Check code formatting
        run: vendor/bin/pint --test
